## Word Embedding Techniques using Embedding Layer in Keras
Word embedding is a technique used in natural language processing (NLP) to convert words into vectors.
The Embedding layer in Keras is used to perform word embedding. It is a type of neural
network layer that maps words to vectors. The Embedding layer is a key component of many NLP
models.
### Embedding Layer in Keras
The Embedding layer in Keras is a type of neural network layer that maps words to vectors.
It is a key component of many NLP models.
### Word Embedding Techniques using Embedding Layer in Keras


In [ ]:
pip install tensorflow


In [8]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [39]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [40]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [30]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [89]:
### Vocabulary size
voc_size=500

### One Hot Representation

In [90]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[461, 298, 229, 437], [461, 298, 229, 316], [461, 339, 229, 172], [29, 370, 18, 71, 52], [29, 370, 18, 71, 248], [295, 461, 342, 229, 419], [350, 213, 149, 71]]



### Word Embedding Represntation

In [74]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [68]:
import numpy as np

In [91]:
## pre padding
sent_length=8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 461 298 229 437]
 [  0   0   0   0 461 298 229 316]
 [  0   0   0   0 461 339 229 172]
 [  0   0   0  29 370  18  71  52]
 [  0   0   0  29 370  18  71 248]
 [  0   0   0 295 461 342 229 419]
 [  0   0   0   0 350 213 149  71]]


In [92]:
## 10 feature dimesnions
dim=10

In [93]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=10, input_shape=(sent_length,)))
model.compile('adam','mse')


In [94]:
model.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_13 (Embedding)        │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [95]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 461, 298, 229, 437])

In [97]:
# Reshape to (1, sent_length) to simulate a batch of size 1
single_doc = np.array(embedded_docs[0]).reshape(1, -1)

# Now pass it to the model for prediction
model.predict(single_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step


array([[[-0.04437944, -0.02334898, -0.04329724,  0.03605784,
          0.01522413, -0.00254602, -0.03372777,  0.0233614 ,
         -0.00821145,  0.01713983],
        [-0.04437944, -0.02334898, -0.04329724,  0.03605784,
          0.01522413, -0.00254602, -0.03372777,  0.0233614 ,
         -0.00821145,  0.01713983],
        [-0.04437944, -0.02334898, -0.04329724,  0.03605784,
          0.01522413, -0.00254602, -0.03372777,  0.0233614 ,
         -0.00821145,  0.01713983],
        [-0.04437944, -0.02334898, -0.04329724,  0.03605784,
          0.01522413, -0.00254602, -0.03372777,  0.0233614 ,
         -0.00821145,  0.01713983],
        [ 0.04855329, -0.03391048, -0.02123376, -0.04045446,
         -0.01232713, -0.03725051,  0.0329395 ,  0.03066463,
          0.02702928, -0.03165245],
        [ 0.04415147,  0.01122659, -0.04268719, -0.04588213,
         -0.01014138, -0.02125028, -0.003663  ,  0.02132566,
         -0.01133956, -0.02142308],
        [-0.00315143,  0.01729933, -0.01114786,  0.0

In [98]:
print(embedded_docs.shape)


(7, 8)


In [99]:
# print(model.predict(embedded_docs))
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 470ms/step
[[[-4.43794392e-02 -2.33489759e-02 -4.32972424e-02  3.60578410e-02
    1.52241327e-02 -2.54602358e-03 -3.37277651e-02  2.33613960e-02
   -8.21144506e-03  1.71398260e-02]
  [-4.43794392e-02 -2.33489759e-02 -4.32972424e-02  3.60578410e-02
    1.52241327e-02 -2.54602358e-03 -3.37277651e-02  2.33613960e-02
   -8.21144506e-03  1.71398260e-02]
  [-4.43794392e-02 -2.33489759e-02 -4.32972424e-02  3.60578410e-02
    1.52241327e-02 -2.54602358e-03 -3.37277651e-02  2.33613960e-02
   -8.21144506e-03  1.71398260e-02]
  [-4.43794392e-02 -2.33489759e-02 -4.32972424e-02  3.60578410e-02
    1.52241327e-02 -2.54602358e-03 -3.37277651e-02  2.33613960e-02
   -8.21144506e-03  1.71398260e-02]
  [ 4.85532917e-02 -3.39104757e-02 -2.12337617e-02 -4.04544584e-02
   -1.23271346e-02 -3.72505076e-02  3.29394974e-02  3.06646340e-02
    2.70292796e-02 -3.16524506e-02]
  [ 4.41514738e-02  1.12265944e-02 -4.26871888e-02 -4.58821319e-02
   -1.01413839e-02 -2.12502833e-02 -3.663003

In [100]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]